# Generated by Django 2.2.2 on 2019-07-19 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=100, null=True)),
                ('address_2', models.CharField(max_length=100, null=True)),
                ('address_3', models.CharField(max_length=100, null=True)),
                ('address_4', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50, null=True)),
                ('postal_code', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CinemaCityCinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_id', models.CharField(max_length=10)),
                ('group_id', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('image_url', models.URLField()),
                ('address', models.CharField(max_length=100)),
                ('booking_url', models.URLField()),
                ('block_online_sales', models.BooleanField()),
                ('block_online_sales_until', models.DateTimeField(null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinemas_repertoire.AddressInfo')),
            ],
        ),
    ]
