# Generated by Django 2.2.2 on 2019-07-19 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas_repertoire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemacitycinema',
            name='address_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemas_repertoire.AddressInfo'),
        ),
        migrations.AlterField(
            model_name='cinemacitycinema',
            name='cinema_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
