# Generated by Django 2.2.2 on 2019-07-19 14:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas_repertoire', '0002_auto_20190719_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaCityMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('poster_link', models.URLField()),
                ('video_link', models.URLField()),
                ('link', models.URLField()),
                ('weight', models.IntegerField()),
                ('release_year', models.IntegerField()),
                ('attribute_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='CinemaCityEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=10, unique=True)),
                ('business_day', models.CharField(max_length=15)),
                ('event_datetime', models.DateTimeField()),
                ('attribute_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('booking_link', models.URLField()),
                ('sold_out', models.BooleanField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas_repertoire.CinemaCityCinema', to_field='cinema_id')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas_repertoire.CinemaCityMovie', to_field='movie_id')),
            ],
        ),
    ]
