# Generated by Django 2.2.2 on 2019-07-22 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas_repertoire', '0003_cinemacityevent_cinemacitymovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemacityevent',
            name='cinema',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cinemas_repertoire.CinemaCityCinema', to_field='cinema_id'),
        ),
        migrations.AlterField(
            model_name='cinemacityevent',
            name='film',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cinemas_repertoire.CinemaCityMovie', to_field='movie_id'),
        ),
    ]
