# Generated by Django 2.2.2 on 2019-07-22 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas_repertoire', '0004_auto_20190722_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemacitycinema',
            old_name='cinema_id',
            new_name='cc_cinema_id',
        ),
        migrations.RenameField(
            model_name='cinemacityevent',
            old_name='event_id',
            new_name='cc_event_id',
        ),
        migrations.RenameField(
            model_name='cinemacitymovie',
            old_name='movie_id',
            new_name='cc_movie_id',
        ),
        migrations.RenameField(
            model_name='cinemacityevent',
            old_name='cinema',
            new_name='cc_cinema',
        ),
        migrations.RenameField(
            model_name='cinemacityevent',
            old_name='film',
            new_name='cc_film',
        ),
    ]
