version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - webnet
    command: python manage.py runserver 0.0.0.0:8000
  db:
    image: postgres:11.4
    volumes:
      - ./shared/postgresql:/var/lib/postgresql/data
    env_file:
      - .envs/.local/.postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
networks:
  webnet: